// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrgDemo.Infrastructure;

#nullable disable

namespace infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251127181428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("OrgDemo.Logic.Organization", b =>
                {
                    b.Property<string>("OrganisasjonsNummer")
                        .HasColumnType("TEXT");

                    b.Property<int>("AntallAnsatte")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Selskapsform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StiftelsesDato")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("OrganisasjonsNummer");

                    b.ToTable("Organizations");
                });
#pragma warning restore 612, 618
        }
    }
}
